"use client";

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    [name: string]: THREE.Mesh
  }
  materials: {
    [name: string]: THREE.Material
  }
}

export function PenthouseWithRoof(props: any) {
  const { nodes, materials } = useGLTF('/models/penthouse_with_roof.glb') as unknown as GLTFResult

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.building_bottom.geometry}
        material={materials.building}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor.geometry}
        material={materials.carrelage_046_ovcolbfbfbfcolpic12contpic03_Room_Entity_Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_sep.geometry}
        material={materials.gris_001_Room_Entity_Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass_ground.geometry}
        material={materials.gazon_007_Room_Entity_Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials['Wood.121']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.buisson___buisson_branche_texture}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_13.geometry}
        material={materials.buisson___buisson_branche_texture}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials.buisson___buisson_texture}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_15.geometry}
        material={materials.carrelage_046_ovcolacacaccolpic12contpic02_Wall_Entity_Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials.carrelage_046_ovcolbfbfbfcolpic12contpic03_Wall_Entity_Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials['Fabric 3']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_19.geometry}
        material={materials.cuisine_evier_001___mat_verni}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials['Laminated Wood']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials.cuisine_ilot_002___mat_verni}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_21.geometry}
        material={materials.cuisine_meuble_bas_001___mat_microonde}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials.cuisine_meuble_bas_001___mat_pied}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_23.geometry}
        material={materials.cuisine_meuble_bas_001___mat_poignet}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials.cuisine_meuble_bas_001___mat_porte}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_25.geometry}
        material={materials.cuisine_meuble_bas_001___mat_verni}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        material={
          materials.cuisine_meuble_bas_003____cuisine_meuble_bas_003_cuisine_meuble_bas_003_cuisine_meuble_bas_003verni
        }
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_27.geometry}
        material={materials['Laminated Wood']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials['Laminated Wood']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_29.geometry}
        material={
          materials.cuisine_plaque_cuisson_001____cuisine_plaque_cuisson_001_cuisine_plaque_cuisson_001_cuisine_plaque_cuisson_00108___default
        }
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={
          materials.cuisine_plaque_cuisson_001____cuisine_plaque_cuisson_001_cuisine_plaque_cuisson_001_cuisine_plaque_cuisson_001metal
        }
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_31.geometry}
        material={
          materials.cuisine_plaque_cuisson_001____cuisine_plaque_cuisson_001_cuisine_plaque_cuisson_001_cuisine_plaque_cuisson_001verni
        }
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_33.geometry}
        material={materials.cypres___mat_cypres_tronc}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_38.geometry}
        material={materials.enduit_004_Room_Entity_Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_39.geometry}
        material={materials.enduit_004_Wall_Entity_Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.baie_vitree_002___verre}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_40.geometry}
        material={materials.fake_mat_0_0_0_255}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_41.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_42.geometry}
        material={materials['Procedural Wood']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_43.geometry}
        material={materials.metal2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_44.geometry}
        material={materials.fake_mat_165_165_165_255}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_46.geometry}
        material={materials.fake_mat_229_229_229_255}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_47.geometry}
        material={materials.fake_mat_248_249_253_255}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_48.geometry}
        material={materials.light2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_48001.geometry}
        material={materials.deer_head}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_48002.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_48003.geometry}
        material={materials['Marble Ceramic']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_48004.geometry}
        material={materials['Marble Ceramic']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_48006.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_49.geometry}
        material={materials.fake_mat_255_255_255_32}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.baie_vitree_002___wood_dormant}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_50.geometry}
        material={materials['Procedural Wood']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_51.geometry}
        material={materials.fenetre_002____fenetre_002fenetre_002_d1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_52.geometry}
        material={materials.fenetre_002____fenetre_002fenetre_002_p1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_53.geometry}
        material={materials.fenetre_002____fenetre_verre}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_54.geometry}
        material={materials.fenetre_029______phong1sg6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_56.geometry}
        material={materials.metal2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_56001.geometry}
        material={materials.metal2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_56002.geometry}
        material={materials.metal2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_56003.geometry}
        material={materials.metal2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_58.geometry}
        material={materials.gris_001_Wall_Entity_Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_59.geometry}
        material={materials.horloge_002___bis_mat_horlogesg}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.beige_006_Wall_Entity_Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_60.geometry}
        material={materials.hotte_003___mat_hote}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_66.geometry}
        material={materials.lave_mains_001___lave_mains_001_blinn4sg}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_67.geometry}
        material={materials.IhanMarble}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_68.geometry}
        material={materials['mirror.nocompress']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_69.geometry}
        material={materials.mur_vegetal_off___phong150}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_70.geometry}
        material={materials.mur_vegetal_off___phong151}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_71.geometry}
        material={materials.mur_vegetal_off___phong31}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_73.geometry}
        material={materials.pack_003_salon_television___material__83}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_76.geometry}
        material={materials.plante_interieur_off___bis_palmier_tronc2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_78.geometry}
        material={materials.plante_vase_off_001___phong37}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_79.geometry}
        material={materials.porte_010___verre}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials['Laminated Wood']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8001.geometry}
        material={materials.flower_pot}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8002.geometry}
        material={materials.flower_pot}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8003.geometry}
        material={materials['Plaster wall']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8004.geometry}
        material={materials['Plaster wall']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8010.geometry}
        material={materials.light2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_80.geometry}
        material={materials.metal2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_81.geometry}
        material={materials.prise_01____prise_prise_prisematerial__126}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_82.geometry}
        material={materials.prise___material__49}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_83.geometry}
        material={
          materials.refrigerateur_006____refrigerateur_006_refrigerateur_006_refrigerateur_006glacon
        }
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_84.geometry}
        material={
          materials.refrigerateur_006____refrigerateur_006_refrigerateur_006_refrigerateur_006porte
        }
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_85.geometry}
        material={materials['Jute Matting']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_86.geometry}
        material={materials.table_basse_016___mat_vitresg}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_87.geometry}
        material={materials.tex_terreau}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_89.geometry}
        material={materials.tissus_030_ovcol868686colpic12contpic00}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials.blanc_001_Room_Entity_Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_90.geometry}
        material={materials.tissus_044_ovcolacacaccolpic12contpic02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_91.geometry}
        material={materials.tissus_065_ovcol868686colpic12contpic00}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_92.geometry}
        material={materials.tissus_071_ovcolacacaccolpic12contpic02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_93.geometry}
        material={materials.vitrine_004___mat_vitresg}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_95.geometry}
        material={materials.wc_005____couvercle}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.outside_floor.geometry}
        material={materials.bitume_001_ovcol737373colpic12contpic11_Room_Entity_Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pine_trees.geometry}
        material={materials.cypres___mat_cypres_feuille}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pool.geometry}
        material={materials.poolTiles}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pool_water.geometry}
        material={materials.texture_eau_piscine_ovcol5ca1d7colpic11contpic01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_pots.geometry}
        material={materials.plante_interieur_off___phong80}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_pots_thin.geometry}
        material={materials.pack_004_salon_001_plante___nopaint_feuilles}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tv_screen_1.geometry}
        material={materials['mirror.nocompress']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tv_screen_2.geometry}
        material={materials['mirror.nocompress']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tv_screen_screen.geometry}
        material={materials['mirror.nocompress']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls.geometry}
        material={materials['Dirty Plaster']}
      />
    </group>
  )
}

useGLTF.preload('/models/penthouse_with_roof.glb')
